const failedPromise = new Promise((resolve, reject) => {
  /* ...code here */
  reject(new Error('Oops, error!'));
});

/*
 * выведите в консоль ошибку в ф-ции onError
 */

failedPromise.catch(function onError(error) {
  /* ...code here */
  console.log(error);
});
